Description: "Basic Budget 100$"
Parameters:
  AdminEmail:
    Description: 'Email address of the Administrator'
Resources:
  BudgetBase:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetLimit:
          Amount: 100
          Unit: USD
        TimeUnit: MONTHLY
        TimePeriod:
          Start: 1225864800
          End: 1926864800
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 99
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Sub ${AdminEmail}
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 75
          Subscribers:
          - SubscriptionType: EMAIL
            Address: !Sub ${AdminEmail}
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 50
          Subscribers:
          - SubscriptionType: EMAIL
            Address: !Sub ${AdminEmail}
Outputs:
  BudgetId:
    Value: !Ref BudgetBase